### ISSUE TITLE
Crown Quals counts Quals incorrectly

### ISSUE THREAD

**Issue by esdraelon** [amtgard/ORK3#186]
Consider user 4, for instance.

**Comment by Glenalth** [comment]
Is the crown qualified report automatically dumping people that have 0 kingdom points even if they have enough ducal points?

It also seems to be counting Ducal monarch as two offices instead of one.

I can use myself as an example that isn't showing up on the Dragonspine report.
https://amtgard.com/ork/orkui/index.php?Route=Player/index/3795
I temporarily added 1 term as Kingdom Champion and then it was displaying as 1 Kingdom and 15 Ducal.

**Comment by esdraelon** [comment]
Reduced crown points for ducal monarchies in db migration, and additional clause to force pulling crown qual'ed duchy-level individuals.
