### ISSUE TITLE
Add an mkdocs directory and output directory for ORK users documentation

### ISSUE THREAD

**Issue by kenwalker** [amtgard/ORK3#247]
This is a suggestion to use mkdocs as a means to generate documentation for the ORK. We're using it at work and it's quite reasonable.  This would make writing doc accessible to all since it's markdown and images.  mkdocs also generates an index for searching.

The workflow would be for changes to be made in an mkdocs subdirectory and the output of the "mkdocs build" would go into a statically served directory on the ORK proper.  I can do some prototyping and add some screenshots to this issue to show what it might look like.

Has any other documentation effort tied to the ORK been thought of before?

[The mkdocs site itself](https://www.mkdocs.org)

**Comment by Glenalth** [comment]
Kind of.... My initial plan for documentation was to crowd source through Google Docs and then link it directly from the ORK, but it turns out people aren't interested in helping write the documentation so it's sat with no edits for over a year now.

If it were built into the ORK with a note that it could be improved/edited it may draw some more attention.

https://docs.google.com/document/d/18wsfFoyD6RXrO4FAxXjfHRTQ0Z_4mWZqzI5f3aH0sNw/edit

**Comment by kenwalker** [comment]
I may do a trial with your initial content and see what you think it looks like in the mkdocs look/feel. Thanks for trying, I didn't know anything about this myself. And thanks for starting the doc.

**Comment by jrtaylor-com** [comment]
Requiring more storage space and processing (static site generation) will likely have an impact on the hosting finances and would require review and approval.

For now, I can easily throw in @Glenalth 's doc link. PR will be attached shortly.

**Comment by kenwalker** [comment]
Will review the other PR. I still thing an integrated documentation solution is required and should be brought up if you think it will impact hosting fee increase.

**Comment by jrtaylor-com** [comment]
I agree, an interactive help system and documentation built into the template would be great. But PR #259 is a stopgap until that can be added.
